---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10.13
        name: postgres
        env:
          - name: POSTGRES_USER
            value: testuser
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: supersecretkey
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: testdatabase
          - name: PGDATA
            value: '/var/lib/postgresql/data/pgdata'
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
